# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: DB_Ticket
    environment:
      POSTGRES_DB: ticket
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    volumes:
    - db_data:/var/lib/postgresql/data
  api:
    image: postgres:latest
    container_name: API
    restart: always
    environment:
      POSTGRES_DB: image
      POSTGRES_PASSWORD: 1234
    ports:
      - 5445:5432
    volumes:
      - api_data:/var/lib/postgresql/data
volumes:
  db_data:
  api_data: